### ISSUE TITLE
Rework Daily Recommendations

### ISSUE THREAD

**Issue by derickso8** [COSC481W-2021Winter/capstone-project-film-club#131]
- [x] Add a timer so that recommendations change daily
- [x] Add the ability to refresh recommendations manually

**Comment by nfishel48** [comment]
Im not sure that setting the recommendations to change daily is possible with the way we have everything set up now. It would require that we change the get_recommendations to be state full and store the recommendations in the database. Since we don't exactly have the money to be running multiple databases for the live site I don't think we want to take up time on the database server pulling recommendations every single time somebody looks at it. Ive set up the recommendations to change every time the page is loaded

**Comment by nfishel48** [comment]
https://github.com/COSC481W-2021Winter/capstone-project-film-club/pull/135

**Comment by ghost** [comment]
#136
